#!/bin/bash
#PBS -N BreakDancer
#PBS -l mem=10g,nodes=1:ppn=2,walltime=18:00:00
#PBS -q paedwy
#PBS -m abe -M boxyjcao@connect.hku.hk
#PBS -o BreakDancer.out
#PBS -e BreakDancer.err
#PBS -V

SV_folder=/home/data/thala_project/SV
BDwkd="$SV_folder"/Screening_stage/BreakDancer
Raw_Bam_file_folder=/home/data/thala_project/Bam_file
BREAKDANCER=/home/software/breakdancer/BD_bins/bin/breakdancer-max
BDBAM2CFG="$SV_folder"/Tailored_SV_thala/tailored_SV_Thala/Screening_stage/BreakDancer/perl/bam2cfg.pl
BD_CHECK_CON_PY="$SV_folder"/Tailored_SV_thala/tailored_SV_Thala/Screening_stage/BreakDancer/Modify_BD_config.py

#-------3. run Breakdancer
# generate BD configure file
mkdir $BDwkd/config
cd $BDwkd/config
for i in all_samples
do
perl $BDBAM2CFG \
-q 30 \
-m \
-h \
-c 5 \
-g \
-v 3 \
$Raw_Bam_file_folder/"$i"/"$i".bam > $BDwkd/config/BD_"$i".cfg
done

# check if the configue file match the symmetric distribution
# if yes, run BreakDancer
# if no, modify the configure file, then run Breakdancer
mkdir $BDwkd/BD_pre
cd $BDwkd
for i in all_samples
do
    if grep -Fq infinity $BDwkd/config/BD_"$i".cfg
        then
            python $BD_CHECK_CON_PY $BDwkd/config/"$i".bam.SeqCap.insertsize_histogram $BDwkd/config/BD_"$i".cfg $BDwkd/config/modified_BD_"$i".cfg
            #run BreakDancer with the new config
            $BREAKDANCER $BDwkd/config/modified_BD_"$i".cfg > $BDwkd/BD_pre/BD_"$i".pre
    else
        #run BreakDancer with the original configure file
        $BREAKDANCER $BDwkd/config/BD_"$i".cfg > $BDwkd/BD_pre/BD_"$i".pre
    fi
done
