#!/bin/bash
#PBS -N RPKM
#PBS -l mem=40g,nodes=1:ppn=5,walltime=18:00:00
#PBS -q paedwy
#PBS -m abe -M boxyjcao@connect.hku.hk
#PBS -o RPKM.out
#PBS -e RPKM.err
#PBS -V

SV_folder=/home/data/thala_project/SV
Raw_Bam_file_folder=/home/data/thala_project/Bam_file
cnvf="$SV_folder"/Conifer
PROBE_FILE="$cnvf"/hg19_probe_coverage.bed
SAMTOOLS=/home/yjcao/software/samtools-1.4/samtools
CONIFER=/home/software/Conifer/conifer.py

for i in all_samples
do
    $SAMTOOLS index $Raw_Bam_file_folder/"$i"/"$i".bam
    python $CONIFER rpkm \
        --probes $PROBE_FILE \
        --input $Raw_Bam_file_folder/"$i"/"$i".bam \
        --output $cnvf/RPKM/"$i".rpkm.txt
done
