#!/bin/bash
#PBS -N pindel
#PBS -l mem=10g,nodes=1:ppn=2,walltime=18:00:00
#PBS -q queue_name_here
#PBS -m abe -M youremail_address_here
#PBS -o pindel.out
#PBS -e pindel.err
#PBS -V

SV_folder=/home/data/thala_project/SV
KNOWN_SV_FILE="$SV_folder"/Tailored_SV_thala/Screening_stage/Pindel/sorted.known_SV_Deletion_100bp.bed
Raw_Bam_file_folder=/home/data/thala_project/Bam_file

#-------1.including folderss
# root folder for PINDEL
Pwkd="$SV_folder"/Screening_stage/Pindel
BDwkd="$SV_folder"/Screening_stage/BreakDancer
#-------2.set software variables
# pindel
PINDEL=/home/software/pindel/pindel
# pindel pindel2vcf
PINDEL2vcf="$SV_folder"/Tailored_SV_thala/Screening_stage/Pindel/pindel2vcf

# run pindel to call sv
REFSEQ=/home/data/reference/GATKbundle/hg19/ucsc.hg19.fasta


# step1: generating configure files for each sample's bam file
mkdir $Pwkd/config/

for i in all_samples
do
    echo -e "$Raw_Bam_file_folder"/"$i"/"$i".bam"\t"400"\t""$i" > $Pwkd/config/P_config_"$i".txt
done

mkdir $Pwkd/P_pre/
mkdir $Pwkd/P_pre/chr16
for i in all_samples
do
$PINDEL -f $REFSEQ \
-i $Pwkd/config/P_config_"$i".txt \
-c chr16 \
-b $BDwkd/BD_pre/BD_"$i".pre \
-o $Pwkd/P_pre/chr16/chr16_BD_Pindel_"$i" \
-r false \
-t false \
-l false \
-k
done

mkdir $Pwkd/P_pre/chr11
for i in all_samples
do
$PINDEL -f $REFSEQ \
-i $Pwkd/config/P_config_"$i".txt \
-c chr11 \
-b $BDwkd/BD_pre/BD_"$i".pre \
-o $Pwkd/P_pre/chr11/chr11_BD_Pindel_"$i" \
-r false \
-t false \
-l false \
-k
done


#find known causal
for chr in chr11 chr16
do
    cd $Pwkd/P_pre/"$chr"
    mkdir Raw_file
    mv ./* Raw_file
    mkdir QCed_Report
    awk 'BEGIN{print "chr\tpos1\tpos2\tsize\tDeletion_with_support_Reads\tsample_name"}'  > ./QCed_Report/Pindel_Deletion.pre
    cd ./Raw_file

    # focusing on deletion only
for i in all_samples
    do
		awk  '{if(/BP_range/ && ($11-$10 >100)){print}}' "$chr"_BD_Pindel_"$i"_D | awk -v Sname=$i '{if($16 >= 5){print $8"\t"$10"\t"$11"\t"$11-$10"\t"$16"\t"Sname}}' >> ../QCed_Report/Pindel_Deletion.pre
	done
	cd ../QCed_Report
done

# find exact mathed SVs
cd $Pwkd/P_pre/chr16/QCed_Report
python "$SV_folder"/Tailored_SV_thala/Screening_stage/Pindel/matching_breakpoint.py -knownbed $KNOWN_SV_FILE -bed Pindel_Deletion.pre -outbed Causal_Pindel_Deletion.pre
cd $Pwkd/P_pre/chr11/QCed_Report
python "$SV_folder"/Tailored_SV_thala/Screening_stage/Pindel/matching_breakpoint.py -knownbed $KNOWN_SV_FILE -bed Pindel_Deletion.pre -outbed Causal_Pindel_Deletion.pre
