#!/bin/bash
#PBS -N BreakDancer
#PBS -l mem=10g,nodes=1:ppn=2,walltime=18:00:00
#PBS -q queue_name_here
#PBS -m abe -M youremail_address_here
#PBS -o BreakDancer.out
#PBS -e BreakDancer.err
#PBS -V

SV_folder=/home/data/thala_project/SV
BDwkd="$SV_folder"/Screening_stage/BreakDancer
Raw_Bam_file_folder=/home/data/thala_project/Bam_file
BREAKDANCER=/home/software/breakdancer/BD_bins/bin/breakdancer-max
BDBAM2CFG="$SV_folder"/Tailored_SV_thala/Screening_stage/BreakDancer/perl/bam2cfg.pl
BD_CHECK_CON_PY="$SV_folder"/Tailored_SV_thala/Screening_stage/BreakDancer/Modify_BD_config.py
KNOWN_SV_FILE="$SV_folder"/Tailored_SV_thala/Screening_stage/BreakDancer/sorted.known_SV_Deletion_100bp.bed

# generate BD configure file
mkdir $BDwkd/config
cd $BDwkd/config
for i in all_samples
do
perl $BDBAM2CFG \
-q 30 \
-m \
-h \
-c 5 \
-g \
$Raw_Bam_file_folder/"$i"/"$i".bam > $BDwkd/config/BD_"$i".cfg
done

# check if the configue file match the symmetric distribution
# if yes, run BreakDancer
# if no, modify the configure file, then run Breakdancer
mkdir $BDwkd/BD_pre
cd $BDwkd
for i in all_samples
do
    if grep -Fq infinity $BDwkd/config/BD_"$i".cfg
        then
            python $BD_CHECK_CON_PY $BDwkd/config/"$i".bam.SeqCap.insertsize_histogram $BDwkd/config/BD_"$i".cfg $BDwkd/config/modified_BD_"$i".cfg
            #run BreakDancer with the new config
            $BREAKDANCER -q 0 $BDwkd/config/modified_BD_"$i".cfg > $BDwkd/BD_pre/BD_"$i".pre
    else
        #run BreakDancer with the original configure file
        $BREAKDANCER -q 0 $BDwkd/config/BD_"$i".cfg > $BDwkd/BD_pre/BD_"$i".pre
    fi
done


# filtering steps
cd $BDwkd/BD_pre
mkdir Raw_file
mv ./* ./Raw_file
mkdir QCed_Report
awk 'BEGIN{print "chr\tpos1\tpos2\tsize\tDeletion_with_support_Reads\tsample_name"}'  > ./QCed_Report/BreakDancer_Deletion.pre
cd $BDwkd/BD_pre/Raw_file
for i in all_samples
do
    awk  -v Sname=$i '{if($7=="DEL" && $10 >= 4 && $8 >= 100){print $1"\t"$2"\t"$5"\t"$8"\t"$10"\t"Sname}}' BD_"$i".pre >> ../QCed_Report/BreakDancer_Deletion.pre
done

cd $BDwkd/BD_pre/QCed_Report

sort -k1,1 -k2,2n BreakDancer_Deletion.pre > mid_sorted_BreakDancer_Deletion.pre

bedtools closest -a mid_sorted_BreakDancer_Deletion.pre -b $KNOWN_SV_FILE -d | awk 'BEGIN{FS=OFS="\t"}{if($14=="0"){print}}' > BD_Causal.mid.bed

python "$SV_folder"/Tailored_SV_thala/Screening_stage/BreakDancer/Find_minimum_range_BreakDancer.py --bed BD_Causal.mid.bed -minbed BD_Causal_mid.pre

sort -k6 BD_Causal_mid.pre > BD_Causal.pre

rm -rf BD_Causal.mid.bed mid_sorted_BreakDancer_Deletion.pre BD_Causal_mid.pre
