#!/bin/bash
#PBS -N MainRun_Conifer
#PBS -l mem=40g,nodes=1:ppn=5,walltime=18:00:00
#PBS -q queue_name_here
#PBS -m abe -M youremail_address_here
#PBS -o MainRun_Conifer.out
#PBS -e MainRun_Conifer.err
#PBS -V

SV_folder=/home/data/thala_project/SV
Raw_Bam_file_folder=/home/data/thala_project/Bam_file
cnvf="$SV_folder"/Screening_stage/Conifer
PROBE_FILE="$SV_folder"/Tailored_SV_thala/Screening_stage/Conifer/hg19_probe_coverage.bed
SAMTOOLS=/home/yjcao/software/samtools-1.4/samtools
CONIFER=/home/software/Conifer/conifer.py
KNOWN_SV_FILE="$SV_folder"/Tailored_SV_thala/Screening_stage/Conifer/sorted.known_SV_Deletion_100bp.bed

source activate conifer
python $CONIFER analyze \
    --probes $PROBE_FILE \
    --rpkm_dir $cnvf/RPKM/ \
    --output $cnvf/analysis.hdf5 \
    --svd 3 \
    --write_svals $cnvf/analysis.s.v.txt \
    --plot_scree $cnvf/analysis.screeplot.png \
    --write_sd $cnvf/analysis.sd_values.txt

python $CONIFER call \
    --input $cnvf/analysis.hdf5 \
    --threshold 0.5 \
    --output $cnvf/CNVcalls.txt

python $CONIFER call \
    --input $cnvf/analysis.hdf5 \
    --threshold 0.3 \
    --output $cnvf/0.3_CNVcalls.txt
source deactivate

# find causal varaints
cd $cnvf
mkdir QCed_Report
awk 'BEGIN{print "chr\tpos1\tpos2\tsize\tDeletion_with_support_Reads\tsample_name"}'  > ./QCed_Report/Conifer_Deletion.pre
awk '{if($4-$3>500  && $5=="del"){print $2"\t"$3"\t"$4"\t"$4-$3"\tNA\t"$1}}' CNVcalls.txt >> ./QCed_Report/Conifer_Deletion.pre

cd ./QCed_Report

sort -k1,1 -k2,2n Conifer_Deletion.pre > mid_sorted_Conifer_Deletion.pre

bedtools closest -a mid_sorted_Conifer_Deletion.pre -b $KNOWN_SV_FILE -d > Conifer_Deletion_Causal.mid.bed

python "$SV_folder"/Tailored_SV_thala/Screening_stage/Conifer/Find_minimum_range_Conifer.py --bed Conifer_Deletion_Causal.mid.bed -minbed Conifer_Deletion_Causal.pre.mid

sort -k6 Conifer_Deletion_Causal.pre.mid > Conifer_Deletion_Causal.pre

rm -rf Conifer_Deletion_Causal.pre.mid Conifer_Deletion_Causal.mid.bed mid_sorted_Conifer_Deletion.pre

# duplication

awk 'BEGIN{print "chr\tpos1\tpos2\tsize\tDeletion_with_support_Reads\tsample_name"}'  > Conifer_Duplication.pre
awk '{if($4-$3>2500  && $5=="dup"){print $2"\t"$3"\t"$4"\t"$4-$3"\tNA\t"$1}}' 0.3_CNVcalls.txt >> Conifer_Duplication.pre
awk '{if($2>219000 && $3<228000){print}}' Conifer_Duplication.pre  | sort -k6 > Alpha_region_Conifer_Duplication.pre
